### ISSUE TITLE
Django: mixer.blend(get_user_model()) - does not hash the password

### ISSUE THREAD

**Issue by denisvolokh** [klen/mixer#118]
Hi,

The user object created with _blend_ function cannot be authenticated with _client.login_
```python
user = mixer.blend(get_user_model())
is_logged_in = client.login(username=user.username, password=user.password)
# is_logged_in is always false
``` 

What is the right way to make an authenticated user?

Thanks,
Denis

**Comment by denisvolokh** [comment]
Looked at the source code and found that mixer is just saving the object. 

I can hash password by myself:

```
from django.contrib.auth.hashers import make_password

user = mixer.blend(
        get_user_model(),
        password=make_password(TEST_PASSWORD)
    )
```

**Comment by ozcanyarimdunya** [comment]
> Looked at the source code and found that mixer is just saving the object.
> 
> I can hash password by myself:
> 
> ```
> from django.contrib.auth.hashers import make_password
> 
> user = mixer.blend(
>         get_user_model(),
>         password=make_password(TEST_PASSWORD)
>     )
> ```

You may set it callable

```python
user = mixer.blend(User, password=lambda: make_password(TEST_PASSWORD))
```
