### ISSUE TITLE
Incompatible with latest version of Faker (`12.1.0`)

### ISSUE THREAD

**Issue by mtilda** [klen/mixer#145]
Using the latest version of Faker (12.1.0) raises the following exception:

```
AttributeError: type object 'Factory' has no attribute '_get_provider_class'
```

The latest version of Faker (published 11 hours ago) [removed the method "_get_provider_class"](https://github.com/joke2k/faker/commit/60f0941a80519ff9106ec1b4dcffcbc7e23139e5#diff-eab89d17cb83f13fdcda34aa81fe74d2e483492d23e4cc20e00f74cc1f5f286a).

This package uses `_get_provider_class` here:
https://github.com/klen/mixer/blob/39ef3b717d4ac9da1824cb9c242fd326fa00ba08/mixer/_faker.py#L33

Disallowing the latest version of Faker seems to fix the problem.

**Comment by gmmcal** [comment]
`_get_provider_class` was renamed to `_find_provider_class` https://github.com/joke2k/faker/commit/60f0941a80519ff9106ec1b4dcffcbc7e23139e5

**Comment by omerfarukabaci** [comment]
In any case, I think `Faker` dependency should be pinned to a specific version.
