### ISSUE TITLE
Toggle commit on or off with blend method

### ISSUE THREAD

**Issue by leebrooks0** [klen/mixer#33]
Can I call #blend(ModelX, commit=False)?
I looked at the source and it didn't look like it but a python beginner so I could have missed something?

**Comment by klen** [comment]
No, because the ModelX could have a field with name "commit". But you could use a context manager.

```python
with mixer.ctx(commit=False):
    instance = mixer.blend(ModelX)
```

or define your own mixer instance
```python
from mixer.backend.django import Mixer

mixer = Mixer(commit=false)
```
