### ISSUE TITLE
Prevent distasteful sample content

### ISSUE THREAD

**Issue by fuhrysteve** [klen/mixer#42]
I'm using mixer to generate sample data for a software demo in a relatively conservative industry. As such, I don't want to be showing a demo of my software and have things like `nasty.new@xvideos.pe` (that's a real world example) show up as an email address - it makes us look immature when we're presenting our software to enterprise clients.

I realize we're not going to eliminate the possibility of suggestive content getting populated from time to time, but I see no reason to invite it.

Would you be open to removing some of the more explicit sample content, or providing a way to disable it? I'd be happy to do some of the work and submit a pull request, just wanted to ask first.

**Comment by klen** [comment]
Mixer uses https://github.com/joke2k/faker for the data generation. Actually I think this issue is related to the Faker package. Thank you for your feedback.

**Comment by fuhrysteve** [comment]
Actually the content I'm concerned about is from this library. See, for example:

https://github.com/klen/mixer/blob/66d03eb7830a7c7fa4a9613acb9781f401819dfc/mixer/_faker.py#L26

**Comment by klen** [comment]
Oh, excuse me, I forgot about the code.

**Comment by klen** [comment]
Have removed `xvideos`. How can I remember, I have taken most popular web sites for the collections.

**Comment by fuhrysteve** [comment]
Thanks!
