### ISSUE TITLE
Peewee backend doesn't commit by default

### ISSUE THREAD

**Issue by mechaxl** [klen/mixer#51]
I found this surprising, and it seems like a bug, but the Peewee backend doesn't save by default. It seems like it should default to committing, like the Django backend does. Here's a simple test case:

```python
from mixer.backend.peewee import mixer
from models import Foo
print(Foo.select().count())  # 0
mixer.blend(Foo)
print(Foo.select().count())  # Still 0, which was unexpected.
```

Doing this works just fine, but it's not documented anywhere that this is required:

```python
with mixer.ctx(commit=True):
    foo = mixer.blend(Foo)
```

**Comment by klen** [comment]
Thank you for the feedback. Have made commit=True for peewee.backend as default.
