### ISSUE TITLE
Does mixer fill data into Django image fields?

### ISSUE THREAD

**Issue by mbrochh** [klen/mixer#69]
Before I dive deep into the code I thought I might as well quickly ask:

I realized that my tests have become incredibly slow and I have pinned down the problem to models that have `ImageFields`. When I use `mixer.blend('app.Model', image=None)`, the test runs in 0.005ms but when I use `mixer.blend('app.Model`)`, then the test runs in 1,123ms (!!!)

Is there a way to globally disable that mixer does anything with Django ImageFields?
##

**Comment by klen** [comment]
Something like this, I assume:


```python
    class MyFactory(GenFactory):
        generators = {
            models.ImageField: lambda: None
        }

    mixer = Mixer(factory=MyFactory)

```

**Comment by mbrochh** [comment]
@klen thanks a lot! This works.
