### ISSUE TITLE
Data generation and UUIDType from SQLAlchemy Utils

### ISSUE THREAD

**Issue by frankrousseau** [klen/mixer#73]
Hello there,

Thank you for mixer, it is a very useful tool. I use it to test an API based on Flask Restful and Postgres. But I face an issue. When I want to use a UUIDType column in my database schema, it is not recognized and Mixer can't give a value to it (this type comes from [SQLAlchemy utils](http://sqlalchemy-utils.readthedocs.io/en/latest/data_types.html#module-sqlalchemy_utils.types.uuid)). 

I tried [this solution](http://stackoverflow.com/questions/26416307/attributeerror-for-custom-types-with-mixer):

```python
from mixer.backend.sqlalchemy import GenFactory
GenFactory.generators[UUIDType] = my_generator
```

But it doesn't work. Do you have any idea about what to do to make it work?

**Comment by frankrousseau** [comment]
I solved my problem by forcing the generator each time I generate objects:

```python
import uuid
mixer.blend(Car, id=uuid.uuid4)
```

**Comment by ei-grad** [comment]
I came to the following solution to use PostgreSQL UUIDs:

```python
from sqlalchemy.dialects import postgresql as pg
from mixer.backend.sqlalchemy import Mixer, GenFactory
from mixer import mix_types

class MyFactory(GenFactory):
    types = dict(GenFactory.types)
    types[pg.UUID] = mix_types.UUID


mixer = Mixer(factory=MyFactory)
```
