### ISSUE TITLE
Update faker version

### ISSUE THREAD

**Issue by austinnichols101** [klen/mixer#76]
mixer 5.5.6 specifies faker==0.7.3.  

The latest version of faker==0.7.10 and includes support for Python 3.6.

**Comment by fabian-marquardt** [comment]
Meanwhile we are at 0.7.17 :smile: 
An update would be highly appreciated!

**Comment by edsono** [comment]
Now at 0.8.17 :)

**Comment by Bernardoow** [comment]
Hi @klen !!

Can We update the faker para last version?

**Comment by klen** [comment]
Thank you. Faker has been updated to version 4.0.0. Faker 5+ will be supported soon.
