### ISSUE TITLE
Registration not work when the field is not required

### ISSUE THREAD

**Issue by hangpark** [klen/mixer#94]
If the field is not required, registration via `mixer.register()` is not applied to blending.

For example of Django, if we had a model:

```python
class MyModel(models.Model):
    non_required_field = models.BooleanField(blank=True, default=False)
```

and a registration:

```python
mixer.register(MyModel, non_required_field=True)
```

blending would give `False` instead of `True` that we registered:

```python
mixer.blend(MyModel).non_required_field # False
```

which is not what I suppose.

**Comment by klen** [comment]
Going to close the issue, because PR is closed now.
