### ISSUE TITLE
Using Mixer with django-taggit

### ISSUE THREAD

**Issue by fusion44** [klen/mixer#97]
Hi!

I use [django-taggit](https://github.com/alex/django-taggit) in my project but I encounter problems with mixer. When I blend models with the TagManager attached I get the following message:
> AttributeError: Mixer (transactions.Transaction): type object 'TaggableManager' has no attribute '_meta'

When i add **mixer.SKIP** to the field I get another error message:
> AttributeError: Mixer (transactions.Transaction): 'TaggableManager' object has no attribute 'm2m_field_name'

Here's some pseudo code how I use the TaggableManager:

    from taggit.managers import TaggableManager

    class Transaction(models.Model):
        # some standard django fields here
        tags = TaggableManager()

    # I add values like this 
    trx = Transaction()
    trx.tags.add("TagA", "TagB")

Can I skip blending for this field completely or better yet define my own handler? Thank you.

**Comment by emacsway** [comment]
:+1:
